server:
  port: 8082

spring:
  application.name: users
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-users"
      register-mbeans: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5433/users
    user: postgres
    password: password

openapi-doc:
  info:
    title: Users Service REST API
    description: Users Service with subscribe functionality
    version: 1.0.0
    contact:
      name: Miroslav Kosiuk
      email: miroslavkosiuk@gmail.com

springdoc:
  swagger-ui: path=/swagger-ui.html
  override-with-generic-response: false